version: "3"

services:
  app:
    build: .
    env_file: .env
    environment:
      HTTP_PORT: 5000
      MONGO_URL: "mongodb://db:27017"
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: db
    volumes:
      - "mongo:/data/db"

volumes:
  mongo: